# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on: 
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2.8.1
      with:
        arguments: bootJar

    - name: Copy Jar file
      run: mv build/libs/$(ls build/libs) app.jar

    - uses: actions/upload-artifact@master
      with:
        name: jar-file
        path: app.jar
        
  build-image:

    runs-on: ubuntu-latest
    needs: build

    steps:

      - uses: actions/checkout@v3
  
      - uses: actions/download-artifact@master
        with:
          name: jar-file
          path: app.jar
  
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
  
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5.0.0
        with:
          file: backend/Dockerfile
          push: true
          tags:
            user/app:latest
